### ISSUE TITLE
Uncaught Error: SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS

### ISSUE THREAD

**Issue by chanzer0** [lxieyang/chrome-extension-boilerplate-react#150]
I am having a similar issue to [this](https://github.com/lxieyang/chrome-extension-boilerplate-react/issues/149). I am trying to inject a content script into a 3rd party website using https, and receiving the following error:
```
Uncaught Error: SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS
    at new SockJS (fanduel.bundle.js:9519:13)
    at new SockJSClient (fanduel.bundle.js:7020:17)
    at initSocket (fanduel.bundle.js:14279:12)
    at ./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=localhost&port=3000&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=false (fanduel.bundle.js:7474:55)
    at options.factory (fanduel.bundle.js:17300:31)
    at __webpack_require__ (fanduel.bundle.js:16758:33)
    at fanduel.bundle.js:17875:11
    at fanduel.bundle.js:17880:12
```

My code is as follows
**manifest.json**
```
{
    "manifest_version": 3,
    "background": { "service_worker": "background.bundle.js" },
    "action": {},
    "permissions": [
        "identity",
        "storage",
        "tabs",
        "activeTab",
        "scripting",
        "downloads"
    ],
    "host_permissions": ["<all_urls>"]
}
```
**index.js (background script)**
```
chrome.windows.create(
	{
		url: "https://www.fanduel.com/history",
		focused: false,
		state: "minimized",
	},
	async (hiddenWindow) => {
		const tab = hiddenWindow.tabs[0];

		const res = await chrome.scripting.executeScript({
			target: { tabId: tab.id },
			files: ["fanduel.bundle.js"],
		});
		console.log(res);
	}
);
```
**fanduel.js (fanduel.bundle.js)**
```
chrome.runtime.sendMessage({
    message: "from fanduel.js",
});
console.log("from fanduel.js");
window.onload = () => {
    chrome.runtime.sendMessage({
        message: "onload event from fanduel.js",
    });

    console.log("onload event from fanduel.js");
};
```

**Comment by chanzer0** [comment]
The only way to workaround this is to execute `npm run build` everytime you make a change and re-load the unpacked extension. Hope this helps solving @lxieyang

**Comment by monokaijs** [comment]
A quick fix for this. In `utils` of project's root folder, look for webserver.js.
Change `server.client.webSocketTransport` to `ws`.
Change `server.webSocketServer` to `ws`.
So it will look like this:
![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)

Restart dev server and the problem is gone 🎉🎉🎉

**Comment by xtava** [comment]
> A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> 
> Restart dev server and the problem is gone 🎉🎉🎉

Thank you!! Absolutely clutch.

**Comment by hadnet** [comment]
> A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> 
> Restart dev server and the problem is gone 🎉🎉🎉

Didn't work, I got [webpack-dev-server] [object Event] error
Stack Trace
contentScript.bundle.js:8007 (logger)
contentScript.bundle.js:8176 (anonymous function)
contentScript.bundle.js:7626 (error)
contentScript.bun

**Comment by monokaijs** [comment]
@hadnet can you provide a full log of error?

**Comment by naps62** [comment]
FYI, if you testing only against local webpages it's enough to set `chrome://flags/#allow-insecure-localhost`

**Comment by hadnet** [comment]
> @hadnet can you provide a full log of error?

Too many issues with this bp. Just gave up and built my own using React 18 + TS + Webpack 5

**Comment by naps62** [comment]
@hadnet is it public? I'd be interested in incorporating some ideas if you happened to get a better setup

**Comment by kiennt** [comment]
> A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> 
> Restart dev server and the problem is gone 🎉🎉🎉

That works for me, thanks :+1:

**Comment by bernardomoraes** [comment]
> A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> 
> Restart dev server and the problem is gone tadatadatada

Well done! worked for me.

**Comment by uri3000** [comment]
It did not work for me I am getting another error:



```
WebSocket connection to 'wss://github.com/ws' failed: 
WebSocketClient @ WebSocketClient.js:16
initWDSSocket @ WDSSocket.js:23
initSocket @ ErrorOverlayEntry.js:83
executeWithRetryAndTimeout @ retry.js:9
runWithRetry @ retry.js:17
setupOverlay @ ErrorOverlayEntry.js:82
runWithPatchedUrl @ patchUrl.js:29
./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js @ ErrorOverlayEntry.js:77
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:8
index.js:561 [webpack-dev-server] Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
```

<img width="848" alt="image" src="https://user-images.githubusercontent.com/7873124/221061520-3852b861-d0b0-4bdb-976c-3d85cc608434.png">

**Comment by monokaijs** [comment]
> It did not work for me I am getting another error:
> 
> ```
> WebSocket connection to 'wss://github.com/ws' failed: 
> WebSocketClient @ WebSocketClient.js:16
> initWDSSocket @ WDSSocket.js:23
> initSocket @ ErrorOverlayEntry.js:83
> executeWithRetryAndTimeout @ retry.js:9
> runWithRetry @ retry.js:17
> setupOverlay @ ErrorOverlayEntry.js:82
> runWithPatchedUrl @ patchUrl.js:29
> ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js @ ErrorOverlayEntry.js:77
> options.factory @ react refresh:6
> __webpack_require__ @ bootstrap:24
> (anonymous) @ startup:7
> (anonymous) @ startup:8
> index.js:561 [webpack-dev-server] Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
> ```
> 
> <img alt="image" width="848" src="https://user-images.githubusercontent.com/7873124/221061520-3852b861-d0b0-4bdb-976c-3d85cc608434.png">

Verify if it's working by do some modifications. In my case, I just ignore the error, it keeps working as the error is unrelevant (maybe).

**Comment by ahmedragabshaban** [comment]
For Developers still getting errors This Should Works 
 ``` publicPath: `http://localhost ``` to ``` publicPath: `wss://localhost```

Try with wss://, which indicates you want a secure WebSocket connection.

If you have your WebSocket server running with your Web server, it will probably use the same security certificate and you do not need to do anything. If it does not work, please check your WebSocket server documentation about how to add certificates and enable wss://.
  ```
  https: true,
    hot: true,
    liveReload: false,
    client: {
      webSocketTransport: 'sockjs',
    },
    webSocketServer: 'sockjs',
    host: 'localhost',
    port: env.PORT,
    static: {
      directory: path.join(__dirname, '../build'),
    },
    devMiddleware: {
      publicPath: `wss://localhost:${env.PORT}/`,
      writeToDisk: true,
    },
    ```

**Comment by MirzaHasnat** [comment]
Make https: true, in webpackdevserver Initialtor  in webserver.js file
![image](https://user-images.githubusercontent.com/40728571/226126463-42af8734-daf4-4f87-9c16-bb5a9a1605eb.png)

**Comment by cmsax** [comment]
> 

This bug will also cause the issue that `content js` is not working. After changed `webserver.js`, it works well.

**Comment by liang7hi** [comment]
> A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> 
> Restart dev server and the problem is gone 🎉🎉🎉

Thanks! This works for me.

**Comment by masihjahangiri** [comment]
> A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> 
> Restart dev server and the problem is gone 🎉🎉🎉

# After applying these changes, when you change anything, the dev server reload the page infinitely (infinity loop)

**Comment by alexburlis** [comment]
> > A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> > Restart dev server and the problem is gone 🎉🎉🎉
> 
> # After applying these changes, when you change anything, the dev server reload the page infinitely (infinity loop)

Exact same issue. Tried all of the solutions from above and more.

**Comment by chanzer0** [comment]
> A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> 
> Restart dev server and the problem is gone 🎉🎉🎉

For anyone still viewing, this solved my issues. The other alternative being building a static package each change (which sucks, but works)

**Comment by alexburlis** [comment]
> > A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> > Restart dev server and the problem is gone 🎉🎉🎉
> 
> For anyone still viewing, this solved my issues. The other alternative being building a static package each change (which sucks, but works)

Did you have any issues with infinite reloading when changing the content script? For some reason it doesn't stop for me.

**Comment by chanzer0** [comment]
> > > A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> > > Restart dev server and the problem is gone 🎉🎉🎉
> > 
> > 
> > For anyone still viewing, this solved my issues. The other alternative being building a static package each change (which sucks, but works)
> 
> Did you have any issues with infinite reloading when changing the content script? For some reason it doesn't stop for me.

No, the hot reloads worked fine for me afterwards

**Comment by FSou1** [comment]
Nothing helped, so I ended up using this boilerplate instead: https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite

**Comment by twigs67** [comment]
I got it working , but the hot loading doesn't seem to work now... or at least for the background page

**Comment by twigs67** [comment]
I tested out @FSou1 suggestion and it works without this issue. I would pay someone to fix this issue for this repo.

**Comment by cworsley4** [comment]
> FYI, if you testing only against local webpages it's enough to set `chrome://flags/#allow-insecure-localhost`

This is the way.

**Comment by cmosguy** [comment]
Things still do infinite loops after editing the `content/index.js`, not sure what to do here.

**Comment by phamvankhang** [comment]
> FYI, if you testing only against local webpages it's enough to set `chrome://flags/#allow-insecure-localhost`

thanks, 
change sockjs to ws and enable chrome allow insecure flag
it's work for me

**Comment by aayush-sinha** [comment]
All tabs opened on chrome goes on infinite reload loop once I make any changes on the code.
I have already changed sockjs to ws and also enable enabled "allow-insecure-flag"

**Comment by megatunger** [comment]
> > FYI, if you testing only against local webpages it's enough to set `chrome://flags/#allow-insecure-localhost`
> 
> thanks, change sockjs to ws and enable chrome allow insecure flag it's work for me


This works for me also, add a notes to here: **You need to remove / add the extension again**

**Comment by megatunger** [comment]
Facing infinite reload loop also. It happened when you made any changes.
Ended up with turned off Hot Reload

**Comment by ajzaradichMV** [comment]
Had a similar issue on my end. I'm loading a content script whenever the extension runs which then sends a message back to the popup. For me, when I would load the extension the first time the content script messages would properly get sent but any time loading the extension after the messages would stop.

A combination below seemed to work well for me:

Change `webSocketTransport: 'sockjs'` to `webSocketTransport: 'ws'`
Change `webSocketServer: 'sockjs'` to `webSocketServer: 'ws'`
Change `https: false` to `https: true`

**Comment by Termtime** [comment]
Alright, I've been dealing with this issue for a few days and found a solution that worked out for me. The TLDR (with some explanatory comments) for the solution is:

## Solution TLDR: 
In `webserver.js`:
- set `hot: false`
- Make sure you are setting the hot entry points manually 
- manually add `HotModuleReplacementPlugin` to the plugin list
- set `client: false`
- set `https: false` (haven't tested with true but I think it should work the same)

Example
```
# webserver.js
...

// Set hot entry points manually
for (let entryName in config.entry) {
  if (excludeEntriesToHotReload.indexOf(entryName) === -1) {
    // Enable HMR for all entries except those in the "notHMR" list
    // See "Manual entry points" in https://webpack.js.org/guides/hot-module-replacement/#enabling-hmr
    config.entry[entryName] = [
      'webpack/hot/dev-server.js',
      `webpack-dev-server/client/index.js?hot=true&hostname=localhost&port=${env.PORT}`,
    ].concat(config.entry[entryName]);
  }
}

// Add HotModuleReplacementPlugin to plugin list
config.plugins = [new webpack.HotModuleReplacementPlugin({})].concat(
  config.plugins || []
);
...

var server = new WebpackDevServer(
  {
    https: false,
    // We do not enable hot mode because we are defining above HMR only for some entries
    hot: false,
    liveReload: false,
    client: false,
    // From here and below the rest of the options don't need changing, just posted the most important ones here for clarity
    host: 'localhost',
    port: env.PORT,
    static: {
      directory: path.join(__dirname, '../build'),
    },
    devMiddleware: {
      publicPath: `http://localhost:${env.PORT}/`,
      writeToDisk: true,
    },
    ...
  }
)
```

## Explanation

Let me preface my explanation by clarifying I am not an expert and this is what I've come to understand from reading documentation and debugging the issue for a few days.

As I understand it, the issue` An insecure SockJS connection may not be initiated from a page loaded over HTTPS ` comes from using `sockjs` as the `webSocketServer` option in the `webserver.js` file.

However, if you change `webSocketServer` to `ws` you will notice that the error is gone but now you will get an infinite refresh loop whenever you refresh a page or make a change to your code. 

This stems from the fact that HMR is enabled for ALL entry points via `hot:true` in the dev server config. Which includes the modules that should not have HMR enabled, content script being the culprit in this case for the infinite reload. If you open the dev console on the webpage that is reloading you will notice that it is attempting to create a websocket connection to the site that you are on currently, this would usually throw an exception when using `sockjs` due to it being insecure and stop further code execution, preventing HMR from attempting to get updates (this is why when using `sockjs` you don't have infinite reload loops), but now that we are using `ws` and no exception is thrown HMR will try to find updates which it will never get and prompt it to refresh the page in search for updates, causing an infinite loop.

To fix this we declare `hot:false` and instead define manual entry points for HMR following webpack's [documentation](https://webpack.js.org/guides/hot-module-replacement/#enabling-hmr). And we also need to explicitly add the `HotModuleReplacementPlugin` that webpack would automatically add when `hot:true`.

## Closing Notes & Improved implementation

If you want to implement an even better version of HMR + the ability to reload the extension automatically when content or background scripts change, you can use [this fork](https://github.com/octohedron/chrome-extension-boilerplate-react) which implements that later feature and apply the changes mentioned to achieve both

**Comment by habibi4webdesign** [comment]
If you're developing in a modern browser that supports native WebSockets and you don't need to worry about network restrictions, you can consider using native WebSockets instead of SockJS. You can do this by setting the client.webSocketTransport and webSocketServer options to 'ws'

**Comment by azretkenzhaliev** [comment]
Faced the same issue, I applied:

> A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> 
> Restart dev server and the problem is gone 🎉🎉🎉

and then I also got:

> It did not work for me I am getting another error:
> 
> ```
> WebSocket connection to 'wss://github.com/ws' failed: 
> WebSocketClient @ WebSocketClient.js:16
> initWDSSocket @ WDSSocket.js:23
> initSocket @ ErrorOverlayEntry.js:83
> executeWithRetryAndTimeout @ retry.js:9
> runWithRetry @ retry.js:17
> setupOverlay @ ErrorOverlayEntry.js:82
> runWithPatchedUrl @ patchUrl.js:29
> ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js @ ErrorOverlayEntry.js:77
> options.factory @ react refresh:6
> __webpack_require__ @ bootstrap:24
> (anonymous) @ startup:7
> (anonymous) @ startup:8
> index.js:561 [webpack-dev-server] Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
> ```
> 
> <img alt="image" width="848" src="https://user-images.githubusercontent.com/7873124/221061520-3852b861-d0b0-4bdb-976c-3d85cc608434.png">

**Comment by azretkenzhaliev** [comment]
Then, I applied several more suggestions:

> Make https: true, in webpackdevserver Initialtor in webserver.js file ![image](https://user-images.githubusercontent.com/40728571/226126463-42af8734-daf4-4f87-9c16-bb5a9a1605eb.png)

> FYI, if you testing only against local webpages it's enough to set chrome://flags/#allow-insecure-localhost

> For Developers still getting errors This Should Works
> `publicPath: http://localhost to  publicPath: wss://localhost`
> 
> Try with wss://, which indicates you want a secure WebSocket connection.

And it worked 👍🏼

**Comment by Colliot2** [comment]
> > A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> > Restart dev server and the problem is gone 🎉🎉🎉
> 
> # After applying these changes, when you change anything, the dev server reload the page infinitely (infinity loop)

Same. Would definitely **recommend not using this boilerplate** due to this reason.

**Comment by nguyenHoang32** [comment]
> A quick fix for this. In `utils` of project's root folder, look for webserver.js. Change `server.client.webSocketTransport` to `ws`. Change `server.webSocketServer` to `ws`. So it will look like this: ![image](https://user-images.githubusercontent.com/42785824/214852834-eb9ac124-3356-452c-a015-92afbd36f959.png)
> 
> Restart dev server and the problem is gone 🎉🎉🎉

But hot reload will run infinite

**Comment by hieunc229** [comment]
I ran into the issue, and found out it was an issue with Brave Shields feature. Disable Trackers and Ads blocking will fix it

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/95#issuecomment-1568225628

**Comment by Austin5925** [comment]
> Then, I applied several more suggestions:
> 
> > Make https: true, in webpackdevserver Initialtor in webserver.js file ![image](https://user-images.githubusercontent.com/40728571/226126463-42af8734-daf4-4f87-9c16-bb5a9a1605eb.png)
> 
> > FYI, if you testing only against local webpages it's enough to set chrome://flags/#allow-insecure-localhost
> 
> > For Developers still getting errors This Should Works
> > `publicPath: http://localhost to  publicPath: wss://localhost`
> > Try with wss://, which indicates you want a secure WebSocket connection.
> 
> And it worked 👍🏼

I tried your solution but that didn't work for me. I still have the issue that wobsocket connection to xxx failed.

**Comment by Anonymous-Humanoid** [comment]
If you're willing to settle with recompiling files on save but no fancy client-side hot reloading, you can remove `@pmmmwh/react-refresh-webpack-plugin` and `react-refresh-typescript`, update your webpack configuration accordingly and use the following web server configuration:
```js
let server = new WebpackDevServer(
    {
        hot: false,
        liveReload: false,
        client: false,
        webSocketServer: false,
        bonjour: false,
        static: {
            directory: path.join(__dirname, '..', 'build'),
        },
        devMiddleware: {
            writeToDisk: true,
        },
    },
    compiler
);
```
With this, your `tsconfig.json` may complain about something along the lines of "bonjour is an implicit entry point", which can be fixed as follows:
```js
{
    "compilerOptions": {
        // ...
        "typeRoots": ["./node_modules/@types"],
    },
    // ...
}
```
With Chrome extensions in particular, there are many instances where recompiling files and reloading them is enough to see changes. However, with scripts, such as state-dependent React components or content scripts, reloading the extension may be necessary. Depends on your use-case.

**Comment by Overtorment** [comment]
solution by @Termtime worked realy well for me and imo should be merged into master as the fix
